# Generated by Django 4.1.5 on 2023-01-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco_usuario', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=40)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('pis', models.IntegerField()),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
    ]
