# Generated by Django 4.1.5 on 2023-01-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='pis',
            field=models.CharField(max_length=11),
        ),
    ]
